CREATE DATABASE ejercicioRepaso;
USE ejercicioRepaso;
CREATE TABLE Servicio(
Cod_ser INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
Acti_ser CHAR(40) NOT NULL
);

CREATE TABLE Soldado(
cod_s INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
nombre_s CHAR(50) NOT NULL,
apellido_s CHAR(50) NOT NULL,
grado_s INT NOT NULL
);

CREATE TABLE CuerpoE(
cod_ce INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
denom_ce CHAR(60) NOT NULL
);

CREATE TABLE Cuartel(
cod_c INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
nombre_c CHAR(50) NOT NULL,
ubic_c CHAR(60) NOT NULL
);
ALTER TABLE Cuartel ADD COLUMN columna_agregada INT NOT NULL AFTER nombre_c;
CREATE TABLE Compania(
num_comp INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
actiP_com CHAR(50) NOT NULL
);

SELECT * FROM Cuartel;