-- MySQL Script generated by MySQL Workbench
-- Mon Sep  5 12:27:21 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ejemplo_producto
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ejemplo_producto` ;

-- -----------------------------------------------------
-- Schema ejemplo_producto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ejemplo_producto` ;
USE `ejemplo_producto` ;

-- -----------------------------------------------------
-- Table `ejemplo_producto`.`CLIENTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ejemplo_producto`.`CLIENTE` ;

CREATE TABLE IF NOT EXISTS `ejemplo_producto`.`CLIENTE` (
  `dni` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `fechaNac` DATE NOT NULL,
  `tlfn` INT NOT NULL,
  PRIMARY KEY (`dni`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ejemplo_producto`.`Proveedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ejemplo_producto`.`Proveedor` ;

CREATE TABLE IF NOT EXISTS `ejemplo_producto`.`Proveedor` (
  `nif` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` TEXT(60) NOT NULL,
  PRIMARY KEY (`nif`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ejemplo_producto`.`PRODUCTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ejemplo_producto`.`PRODUCTO` ;

CREATE TABLE IF NOT EXISTS `ejemplo_producto`.`PRODUCTO` (
  `codigo` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL DEFAULT 'ninguno',
  `precio` DECIMAL NOT NULL DEFAULT 0.0,
  `Proveedor_nif` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_PRODUCTO_Proveedor1_idx` (`Proveedor_nif` ASC) VISIBLE,
  CONSTRAINT `fk_PRODUCTO_Proveedor1`
    FOREIGN KEY (`Proveedor_nif`)
    REFERENCES `ejemplo_producto`.`Proveedor` (`nif`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ejemplo_producto`.`COMPRA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ejemplo_producto`.`COMPRA` ;

CREATE TABLE IF NOT EXISTS `ejemplo_producto`.`COMPRA` (
  `CLIENTE_dni` INT NOT NULL,
  `Proveedor_nif` INT NOT NULL,
  PRIMARY KEY (`CLIENTE_dni`, `Proveedor_nif`),
  INDEX `fk_CLIENTE_has_Proveedor_Proveedor1_idx` (`Proveedor_nif` ASC) VISIBLE,
  INDEX `fk_CLIENTE_has_Proveedor_CLIENTE_idx` (`CLIENTE_dni` ASC) VISIBLE,
  CONSTRAINT `fk_CLIENTE_has_Proveedor_CLIENTE`
    FOREIGN KEY (`CLIENTE_dni`)
    REFERENCES `ejemplo_producto`.`CLIENTE` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CLIENTE_has_Proveedor_Proveedor1`
    FOREIGN KEY (`Proveedor_nif`)
    REFERENCES `ejemplo_producto`.`Proveedor` (`nif`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
